### ISSUE TITLE
GD-57: Await on C# executor throws error on non-existing signal `ExecutionCompleted` 

### ISSUE THREAD

**Issue by ngburke** [MikeSchulze/gdUnit4Net#57] opened 2024-03-07 09:24 UTC
### The used GdUnit4 version

4.2.1 (Pre Release/Master branch)

### The used Godot version

v4.2.1.stable.mono.official [b09f793f5]

### Operating System

macOS Ventura

### Describe the bug

When running a long set of C# test suites, after ~50% of them complete and pass I hit the following error. Once this fires, the tests no longer run as the runner has crashed.

`E 0:00:11:0413   GdUnitRunner.gd:83 @ _process(): In Object of type 'RefCounted': Attempt to connect nonexistent signal '' to callable 'GDScriptFunctionState::_signal_callback'.
  <C++ Error>    Condition "!signal_is_valid" is true. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   core/object/object.cpp:1344 @ connect()
  <Stack Trace>  GdUnitRunner.gd:83 @ _process()
`

Some context showing where the error was triggered is in the screenshot below:

<img width="1285" alt="Screenshot 2024-03-06 at 11 15 25 PM" src="https://github.com/MikeSchulze/gdUnit4/assets/7350691/c35cf4f9-dd9f-4b6e-9523-cd0dd8a1277f">

### Steps to Reproduce

Very difficult to nail this down to a smaller test case. I only saw this begin after accumulating test suites after some time. Attempting to disable certain test suites only makes the problem happen on the next test suite after the disabled one.

**Comment by MikeSchulze** [comment] 2024-03-29 08:56
It looks like it could be fixed by https://github.com/godotengine/godot/issues/84254

**Comment by MikeSchulze** [comment] 2024-04-14 07:32
I'm not able to reproduce with GdUnit4 v4.2.4 and GdUnit4Net v4.2.2

```bash
Godot Engine v4.2.1.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Der Blend-Dateiimport ist in den Projekteinstellungen aktiviert, aber es wurde kein Blender-Pfad in den Editoreinstellungen festgelegt. Es werden keine Blend-Dateien importiert.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
Loading GdUnit4 Plugin success
GdUnit4Net version '4.2.2.0' loaded.
GdUnit4: Test server successfully started checked port: 31002
```
cs project file
```xml
<Project Sdk="Godot.NET.Sdk/4.2.1">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <LangVersion>11.0</LangVersion>
    <!--Force nullable warnings, you can disable if you want-->
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!--Disable warning of invalid/incompatible GodotSharp version-->
    <NoWarn>NU1605</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <!--Required for GdUnit4-->
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="gdUnit4.api" Version="4.2.*-*" />
    <PackageReference Include="gdUnit4.test.adapter" Version="1.*" />
  </ItemGroup>
</Project>
```

Test template:
```cs
// GdUnit generated TestSuite
using Godot;
using GdUnit4;
using System;
using System.Threading.Tasks;

namespace GdUnit4
{
	using static Assertions;
	using static Utils;

	[TestSuite]
	public partial class ExampleTestSuite9
	{
		[TestCase]
		public async Task IsFooAsync()
		{
			await ISceneRunner.SyncPhysicsFrame;
			AssertThat("Foo").IsEqual("Foo");
		}

		[TestCase]
		public async Task IsBarAsync()
		{
			await ISceneRunner.SyncPhysicsFrame;
			AssertThat("Foo").IsEqual("Foo");
		}
	}
}
```


![image](https://github.com/MikeSchulze/gdUnit4Net/assets/347037/4bfa4e0e-da34-4d7e-a2f9-5deee498b5f7)

**Closed by MikeSchulze** 2024-04-14 07:32 UTC
Labels: bug, godot related issue
